name: Update RSS feed

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"   # every minute 15 of every hour of every day

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install feedgen
          pip install feedparser
          pip install PyGithub
          pip install python-decouple


      - name: Set Github token
        run: echo "GH_TOKEN=${{ secrets.FEED_GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: test auth
        run: gh api user

      - name: Generate feed
        run: |
          python main.py

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add feed.xml
          git commit -m "Update RSS feed" || exit 0
          git push
